/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zofia.frontend;

import com.zofia.datastructures.graph.Graph;
import com.zofia.datastructures.graph.Vertex;
import com.zofia.drivers.FileDriver;
import com.zofia.drivers.VertexDriver;
import com.zofia.lexer.FileLexer;
import com.zofia.parser.FileParser;
import java.io.IOException;
import java.io.StringReader;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;

/**
 *
 * @author zofia
 */
public class PrincipalFrame extends javax.swing.JFrame {
    
    private String file;
    private String path;
    private FileDriver fileDriver;
    private FileLexer lexer;
    private FileParser parser;
    private VertexDriver driver;
    private String[] places;
    private String[] vehicleRoutes;
    private String[] walkingRoutes;
    private Graph generalGraph;
    
    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
        this.fileDriver = new FileDriver();
        panelVisibility(false);
        frameSize(1005, 695);
        fillVector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JLayeredPane();
        secondaryPanel = new javax.swing.JPanel();
        separator7 = new javax.swing.JSeparator();
        navigationPanel7 = new javax.swing.JPanel();
        originLabel = new javax.swing.JLabel();
        destinationLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        origin = new javax.swing.JComboBox<>();
        destination = new javax.swing.JComboBox<>();
        type = new javax.swing.JComboBox<>();
        optionsPanel = new javax.swing.JPanel();
        routeType = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        customSeparator = new javax.swing.JLabel();
        movementPanel = new javax.swing.JPanel();
        registrationLabel = new javax.swing.JLabel();
        movementRegistration = new javax.swing.JComboBox<>();
        movementButton = new javax.swing.JButton();
        bar = new javax.swing.JPanel();
        fileButton = new javax.swing.JButton();
        navigationButton = new javax.swing.JButton();
        buttonSeparator = new javax.swing.JSeparator();
        scroll = new javax.swing.JScrollPane();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guatemala's Waze");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        secondaryPanel.setBackground(new java.awt.Color(0, 102, 102));
        secondaryPanel.setForeground(new java.awt.Color(0, 0, 0));

        separator7.setForeground(new java.awt.Color(255, 255, 255));

        navigationPanel7.setBackground(new java.awt.Color(255, 255, 255));
        navigationPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Navigation", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        originLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        originLabel.setText("Origin:");

        destinationLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        destinationLabel.setText("Destination:");

        typeLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        typeLabel.setText("Movement:");

        origin.setBackground(new java.awt.Color(255, 255, 255));
        origin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        destination.setBackground(new java.awt.Color(255, 255, 255));
        destination.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        type.setBackground(new java.awt.Color(255, 255, 255));
        type.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vehicle", "Walking" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanel7Layout = new javax.swing.GroupLayout(navigationPanel7);
        navigationPanel7.setLayout(navigationPanel7Layout);
        navigationPanel7Layout.setHorizontalGroup(
            navigationPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(navigationPanel7Layout.createSequentialGroup()
                        .addGroup(navigationPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(originLabel)
                            .addComponent(destinationLabel))
                        .addGap(4, 4, 4)
                        .addGroup(navigationPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(origin, 0, 150, Short.MAX_VALUE)
                            .addComponent(destination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(navigationPanel7Layout.createSequentialGroup()
                        .addComponent(typeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(type, 0, 150, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navigationPanel7Layout.setVerticalGroup(
            navigationPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(navigationPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(originLabel))
                .addGap(18, 18, 18)
                .addGroup(navigationPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destinationLabel)
                    .addComponent(destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(navigationPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        optionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        optionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Options", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        routeType.setBackground(new java.awt.Color(255, 255, 255));
        routeType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        routeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Route type-" }));

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        searchButton.setBorder(null);

        customSeparator.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        customSeparator.setText("-------------------------------------------");

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(routeType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addComponent(customSeparator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(routeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPanelLayout.createSequentialGroup()
                        .addComponent(customSeparator)
                        .addGap(25, 25, 25))
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        movementPanel.setBackground(new java.awt.Color(255, 255, 255));
        movementPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Movements", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Dialog", 0, 12))); // NOI18N

        registrationLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        registrationLabel.setText("Registration:");

        movementRegistration.setBackground(new java.awt.Color(255, 255, 255));
        movementRegistration.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        movementRegistration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        movementButton.setBackground(new java.awt.Color(255, 255, 255));
        movementButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        movementButton.setForeground(new java.awt.Color(0, 0, 0));
        movementButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/walking.png"))); // NOI18N
        movementButton.setText("Move");

        javax.swing.GroupLayout movementPanelLayout = new javax.swing.GroupLayout(movementPanel);
        movementPanel.setLayout(movementPanelLayout);
        movementPanelLayout.setHorizontalGroup(
            movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registrationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movementRegistration, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(movementPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(movementButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        movementPanelLayout.setVerticalGroup(
            movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movementPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(movementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationLabel)
                    .addComponent(movementRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(movementButton))
        );

        javax.swing.GroupLayout secondaryPanelLayout = new javax.swing.GroupLayout(secondaryPanel);
        secondaryPanel.setLayout(secondaryPanelLayout);
        secondaryPanelLayout.setHorizontalGroup(
            secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator7, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(secondaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navigationPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movementPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        secondaryPanelLayout.setVerticalGroup(
            secondaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondaryPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(navigationPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(movementPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bar.setBackground(new java.awt.Color(0, 102, 102));

        fileButton.setBackground(new java.awt.Color(0, 102, 102));
        fileButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        fileButton.setForeground(new java.awt.Color(255, 255, 255));
        fileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file.png"))); // NOI18N
        fileButton.setText("File");
        fileButton.setBorder(null);
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        navigationButton.setBackground(new java.awt.Color(0, 102, 102));
        navigationButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        navigationButton.setForeground(new java.awt.Color(255, 255, 255));
        navigationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/location.png"))); // NOI18N
        navigationButton.setText("Navigate");
        navigationButton.setBorder(null);
        navigationButton.setEnabled(false);
        navigationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigationButtonActionPerformed(evt);
            }
        });

        buttonSeparator.setForeground(new java.awt.Color(255, 255, 255));
        buttonSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout barLayout = new javax.swing.GroupLayout(bar);
        bar.setLayout(barLayout);
        barLayout.setHorizontalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barLayout.setVerticalGroup(
            barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barLayout.createSequentialGroup()
                .addGroup(barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navigationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/map.png"))); // NOI18N
        image.setMaximumSize(new java.awt.Dimension(1000, 558));
        image.setMinimumSize(new java.awt.Dimension(1000, 558));
        scroll.setViewportView(image);

        imagePanel.setLayer(secondaryPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        imagePanel.setLayer(bar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        imagePanel.setLayer(scroll, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(secondaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navigationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigationButtonActionPerformed
        // TODO add your handling code here:
        panelVisibility(true);
        frameSize(1287, 695);
    }//GEN-LAST:event_navigationButtonActionPerformed

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        // TODO add your handling code here:
        this.file = "";
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Open settings file");
        if(chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            this.path = chooser.getSelectedFile().getPath();
            try {
                this.file = fileDriver.readInputFile(path);
                this.lexer = new FileLexer(new StringReader(file));
                this.parser = new FileParser(lexer);
                this.parser.parse();
                
                this.driver = parser.getDriver();
                this.generalGraph = new Graph(driver.getVertexes(), driver.getEdges());
                setPlaces(driver.getVertexes());
                buttonAvailability();
                
            } catch (IOException ex) {
                System.out.println("No se encontro el archivo");
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_fileButtonActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
        if(type.getModel().getSelectedItem().equals("Vehicle")) {
            this.routeType.setModel(new DefaultComboBoxModel<>(vehicleRoutes));
        } else {
            this.routeType.setModel(new DefaultComboBoxModel<>(walkingRoutes));
        }
    }//GEN-LAST:event_typeActionPerformed
    
    /* Preferred size of principal frame */
    private void frameSize(int width, int height) {
        this.setSize(width, height);
    }
    
    /* Secondary panel visibility */
    private void panelVisibility(boolean value) {
        this.secondaryPanel.setVisible(value);
    }
    
    /* 
     * Llena las cajas de seleccion con los 
     * lugares ingresados en el archivo de entrada
    */
    private void setPlaces(List<Vertex> vertex) {
        this.places = new String[vertex.size()];
        for (int i = 0; i < places.length; i++) {
            places[i] = vertex.get(i).getName();
        }
        origin.setModel(new DefaultComboBoxModel<>(places));
        destination.setModel(new DefaultComboBoxModel<>(places));
        movementRegistration.setModel(new DefaultComboBoxModel<>(places));
    }
    
    private void buttonAvailability() {
        this.fileButton.setEnabled(false);
        this.navigationButton.setEnabled(true);
    }
    
    private void fillVector() {
        this.vehicleRoutes = new String[] {"Mejor ruta segun gasolina", "Peor ruta segun gasolina",
            "Mejor ruta segun distancia", "Peor ruta segun distancia", "Mejor ruta segun gasolina y distancia",
            "Peor ruta segun gasolina y distancia"};
        this.walkingRoutes = new String[] {"Mejor ruta segun desgaste fisico", "Peor ruta segun desgaste fisico",
            "Mejor ruta segun distancia", "Peor ruta segun distancia", "Mejor ruta segun desgaste fisico y distancia",
            "Peor ruta segun desgaste fisico y distancia"};
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bar;
    private javax.swing.JSeparator buttonSeparator;
    private javax.swing.JLabel customSeparator;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JButton fileButton;
    private javax.swing.JLabel image;
    private javax.swing.JLayeredPane imagePanel;
    private javax.swing.JButton movementButton;
    private javax.swing.JPanel movementPanel;
    private javax.swing.JComboBox<String> movementRegistration;
    private javax.swing.JButton navigationButton;
    private javax.swing.JPanel navigationPanel7;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JComboBox<String> origin;
    private javax.swing.JLabel originLabel;
    private javax.swing.JLabel registrationLabel;
    private javax.swing.JComboBox<String> routeType;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel secondaryPanel;
    private javax.swing.JSeparator separator7;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
