
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.zofia.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLACE = 5;
  public static final int DOUBLE = 7;
  public static final int error = 1;
  public static final int LESSTHAN = 2;
  public static final int GREATERTHAN = 3;
  public static final int VERTICALBAR = 4;
  public static final int EOF = 0;
  public static final int INT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LESSTHAN",
  "GREATERTHAN",
  "VERTICALBAR",
  "PLACE",
  "INT",
  "DOUBLE"
  };
}

